# Netlify configuration file

[build]
  base = "frontend/frontend"
  publish = "public"
  command = "npm install"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 