# Netlify configuration file

[build]
  # Set base directory to the frontend folder only
  base = "frontend"
  command = "npm install"
  # Publish directory relative to base
  publish = "./public"
  functions = "../netlify/functions"

[functions]
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 