[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "frontend/public"

[functions]
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"
  included_files = ["frontend/public/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 