# Netlify configuration file

[build]
  base = "frontend"
  command = "npm install"
  publish = "frontend/public/"
  functions = "frontend/netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[functions]
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 