# Netlify configuration file

[build]
  command = "cd /opt/build/repo/frontend && npm install"
  publish = "/opt/build/repo/frontend/public"

[functions]
  external_node_modules = ["express", "mongoose"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 