services:
  # Frontend static site
  - type: web
    name: workout-tracker-frontend
    env: static
    buildCommand: cd frontend && npm install && cp -r views/* public/
    staticPublishPath: ./frontend/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0

  # Backend API service
  - type: web
    name: workout-tracker-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /health
    port: 10000 